Feature/issue 15 remove inactive services
pg-irc/pathways-mongo pull request #24
Opened 2021-06-29 18:43 UTC by rasmus-storjohann-PG

2021-07-02 16:50 UTC, brandon-PG requested changes
Looks good. Just one test that I would add

2021-07-02 16:50 UTC, brandon-PG commented on src/__tests__/inactive_records.test.js
> +            it('marks organization with physical address in TN as inactive', async () => {
Add a test for passing state_province properties

2021-07-06 21:34 UTC, brandon-PG approved these changes
All tests pass

2021-07-06 21:44 UTC, ian-lin-PG approved these changes

2021-07-06 21:48 UTC, merged