Feature/issue 44 fix algolia output
pg-irc/pathways-mongo pull request #47
Opened 2021-09-17 23:58 UTC by brandon-PG

2021-09-19 23:37 UTC, rasmus-storjohann-PG requested changes
Wow, a lot of really good work here. I have a few comments but nothing really serious. I see some intermittent failures which can be frustrating, very likely causes by race conditions. Some of those failures may be consistent which would be bad. Let's talk tomorrow.

2021-09-19 23:37 UTC, rasmus-storjohann-PG commented on src/__tests__/parent_organization_pipeline.test.js
> +            expect(result[0].parentOrganization.name).toEqual(organizationName);
Form the assert, it looks like the organization collection is not really needed here, since the organization id is there in the service record. However, it is actually needed because you pull other organization properties out as well, correct? So that can be shown with one or two more asserts here, which would make the test way more meaningful.

2021-09-19 23:37 UTC, rasmus-storjohann-PG commented on src/build_add_service_count_pipeline.js
> +const buildAddServiceCountToOrganizationPipeline = (serviceCountCollName) => [
OK, here clearly the buildFooPipeline naming convention is getting too heavy. Feel free to rename this to something more sensible.

2021-09-19 23:37 UTC, rasmus-storjohann-PG commented on bin/process.js
> +        ...setRegionalPostfixOnKeys(['_id','id'], region),
Not sure if there is a way to not have both 'id' and '_id' columns. I know we need to have 'id' columns once we export to Algolia...

2021-09-19 23:37 UTC, rasmus-storjohann-PG commented on bin/process.js
> +};
Clean and tidy, I really like this. Only thing is the name, which doesn't reflect the last step which has nothing to do with the count... That is very minor though.

2021-09-19 23:37 UTC, rasmus-storjohann-PG commented on src/__tests__/add_service_count_pipeline.test.js
> +        it('Get service count value from foriegn collection', async () => {
So I'm not sure what a "foreign" collection is. Also, typo.

2021-09-19 23:37 UTC, rasmus-storjohann-PG commented on src/__tests__/add_service_count_pipeline.test.js
> +            );
Yeah, I'm not clear on what these two counts are doing here...

2021-09-19 23:38 UTC, rasmus-storjohann-PG commented on bin/process.js
>          { $merge: outputCollName },
This problem was fixed in subsequent commits

2021-09-20 17:11 UTC, brandon-PG commented on src/pipelines/build_services_pipeline.js
> +                    }
ifNull only changes the value if the first object in the array, '$address.address_1' in this case, is null. Otherwise the value  remains the same.

2021-09-20 18:45 UTC, brandon-PG commented on src/pipelines/build_services_pipeline.js
> +                        $gte: [ '$address.address_2', null ]
$ne does not work. I have changed the gte instances to ifNull.

2021-09-20 20:15 UTC, brandon-PG commented on src/__tests__/add_service_count_pipeline.test.js
> +describe('aggregation', () => {
All of our tests share this top level `describe('aggregation'`. Should I still change this one?

2021-09-22 21:52 UTC, merged