Feature/issue 1676 Add french search terms
pg-irc/pathways-mongo pull request #61
Opened 2021-10-19 22:02 UTC by brandon-PG

2021-10-20 16:04 UTC, rasmus-storjohann-PG commented on src/add_french_topic_names.js
> +    await dropCollectionSafely(db, recommendationsCollectionName);
Ambiguous ownership of this collection: It's good practice to make sure that the thing that creates a thing, also is responsible for destroying that thing. Alternatively, who effectively transfer ownership of the thing from the entity that creates it to the entity that destroys it. It's fine to do that if there is good reason, but it does complicate the code quite a bit.

2021-10-20 16:06 UTC, rasmus-storjohann-PG commented on src/add_french_topic_names.js
> +const createTopicNameMap = async (db, collectionName) => {
`collectionName` is a very generic name, which implies that any collection can be passed in here. I suggest giving the parameter a name that clearly identifies the collection that you expect. `document` below is also totally generic, use more specific terms to make the code clearer. Also I notice that this function specifically pulls out `fr` titles, so the function name can be renamed to state much more explicitly what it does, how about `buildMapFromIdToFrenchTitle()`?

2021-10-20 16:11 UTC, rasmus-storjohann-PG commented on src/add_french_topic_names.js
> +    });
Let's talk about this code and see if we can come up with some higher level Ramda algorithms that do the same thing, I expect that you will make the code much clearer in the process.

2021-10-20 16:12 UTC, rasmus-storjohann-PG commented on src/add_french_topic_names.js
> +    const documents = await recommendations.find().toArray();
`documents` is very generic, a more specif name will make the code easier to follow.

2021-10-20 16:13 UTC, rasmus-storjohann-PG commented on src/__tests__/add_french_topic_names.test.js
> +    it ('Adds the french title from the matching topic id', async () => {
I like how you are using `aString()` in this test, exactly as I would do it.

2021-10-20 16:15 UTC, rasmus-storjohann-PG commented on src/__tests__/add_french_topic_names.test.js
> +        await recommendationCollection.insertOne(recommendationObject);
I have a feeling that you are using the recommendation collection in ways that go a little bit beyond what it was intended to do, thereby breaking the SRP for that collection. We can discuss.

2021-10-20 16:23 UTC, rasmus-storjohann-PG commented on bin/process.js
> +        await addFrenchTopicNames(db, 'topics', 'recommendationsMb');
By the commit message, you add to the `topicsMb` collection, but by the code you add to the entire `topics` collection. Would it work to move this line one line up and pass in `topicsMb` instead?

2021-10-20 16:24 UTC, rasmus-storjohann-PG commented on src/pipelines/build_services_pipeline.js
> +            translated_topic_names: '$related_topics.translated_topic_names'
Hmm, it really feels like you're piggybacking on an existing collection that is meant for something else...

2021-10-20 16:25 UTC, rasmus-storjohann-PG commented on bin/validate_algolia_json.js
> +        related_topics: related_topics,
Oh so this validation would have totally failed until this change? Whoops

2021-11-01 19:30 UTC, rasmus-storjohann-PG commented on src/add_french_topic_names.js
> +};
So the pattern we have used for pretty much everything in the mongo backend is that of aggregation pipelines, which takes a record, does something to it, and saves it/passes it on to the next stage. Your function here follows exactly the same pattern, you iterate over the services, computes some data and attaches it to the service and stores it. However, you don't use aggregation to do so, I am not sure why. Consistency in approach is very useful property of a code base, so unless there is some compelling reason to do it this way, I would prefer to see this done as an additional stage in the service pipeline.

2021-11-01 19:34 UTC, rasmus-storjohann-PG commented on src/add_french_topic_names.js
> +};
Have a look at `build_services_pipeline.js` and see if you can make it fit along the same pattern as some of the `$set` clauses. Avoid adding more to an existing `$project` clause as was done with the phone numbers, that breaks the SRP since `$project` is for pulling out fields from a document, not doing complicated processing.

2021-11-01 19:44 UTC, rasmus-storjohann-PG commented on bin/validate_algolia_json.js
> +const translated_topic_titles = {
So then we need to make some changes to algolia to ensure that this field is included in the searchable terms. How well does this scale to many languages. Would we ultimately be wanting to pass the currently selected locale to algolia and then just search for terms in that language? Because now it looks like we'd have no option but to search in all the languages, which might be fine or might cause problems.

2021-11-01 19:45 UTC, rasmus-storjohann-PG requested changes
I suggested some changes. Sorry I've taken a long time to come around to looking at this.

2021-11-02 18:33 UTC, brandon-PG commented
Creating a new pr for the changes which will be made because they are completely different than the current solution

2021-11-02 18:33 UTC, closed without merging